name: maplibre_gl
description: A Flutter plugin for integrating MapLibre Maps inside a Flutter application on Android, iOS and web platforms.
version: 0.20.0
repository: https://github.com/maplibre/flutter-maplibre-gl
issue_tracker: https://github.com/maplibre/flutter-maplibre-gl/issues
publish_to: none


environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter
  maplibre_gl_platform_interface:
    path: ../maplibre_gl_platform_interface


dev_dependencies:
  very_good_analysis: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: org.maplibre.maplibregl
        pluginClass: MapLibreMapsPlugin
      ios:
        pluginClass: MapLibreMapsPlugin
      web:
        default_package: maplibre_gl_web

platforms:
  android:
  ios:
  web:
